default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: <%= Settings.db.pool || 5 %>
  host: <%= Settings.db.host %>
  port: <%= Settings.db.port %>
  username: <%= Settings.db.username %>
  password: <%= Settings.db.password %>

development:
  <<: *default
  database: <%= Settings.db.name %>_development

test:
  <<: *default
  database: <%= Settings.db.name %>_test

production:
  <<: *default
  database: <%= Settings.db.name %>_production
